#!/usr/bin/env python3
from sys import exit
from src.ensure_args import ensure_args
from src.find_config import find_config
from src.parse_yaml import parse_yaml
from src.compute_arguments import compute_arguments
from src.invoke_spm import invoke_spm

args = ensure_args()
config_path = find_config()
data = parse_yaml(config_path)
spm_arg = compute_arguments(args, data)
invoke_spm(spm_arg)
exit(0)