#!/usr/bin/env python3
from sys import exit
from src.ensure_args import ensure_args
from src.parse_yaml import parse_yaml
from src.compute_arguments import compute_arguments
from src.invoke_spm import invoke_spm
from src.resolve_yaml import resolve_yaml

args = ensure_args()
data = resolve_yaml()
spm_arg = compute_arguments(args, data)
invoke_spm(spm_arg)
exit(0)